//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptiveLearningFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseQuestions = new HashSet<CourseQuestion>();
        }
    
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> TopicId { get; set; }
        public Nullable<int> ClassLevel { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual ICollection<CourseQuestion> CourseQuestions { get; set; }
    }
}
