//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptiveLearningFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningStyle
    {
        public int LearningStyleID { get; set; }
        public string LearningType { get; set; }
        public string LearningStyle1 { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
