//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptiveLearningFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Courses = new HashSet<Course>();
            this.UserTopics = new HashSet<UserTopic>();
        }
    
        public int TopicId { get; set; }
        public string TopicName { get; set; }
        public string TopicDescription { get; set; }
    
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<UserTopic> UserTopics { get; set; }
    }
}
